### ISSUE TITLE
NOT WORKING!

### ISSUE THREAD

**Issue by canyazbahar** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#22]
tried every methhod and finally uninstalled it.

**Comment by ezxpro** [comment]
This is not a very descriptive issue. Not sure how the developer is going to help you when:
1. You don't mention what issue you're having nor any information about it at all
2. You uninstalled it, so apparently you moved on after trying it, so you might as well not have wasted your time creating this issue.

**Comment by canyazbahar** [comment]
creating this issue?? I wrote it so that everyone who came after me would see this message and say "oh it' not just me". anyways i think u are wasting ur time here too, cause creator dont even look at the issues.

**Comment by danielduckworth** [comment]
> This is not a very descriptive issue. Not sure how the developer is going to help you when:
> 
> 1. You don't mention what issue you're having nor any information about it at all
> 2. You uninstalled it, so apparently you moved on after trying it, so you might as well not have wasted your time creating this issue.
> 
> In my case, it's not working either. It throws an exception when I try to search anything. Token is set up and the plugin says it's "valid" in the logs.
> 
> ```
> Please open new issue in: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch/issues/new
> 1. upload log file: C:\Users\ezbie\AppData\Roaming\FlowLauncher\Logs\1.10.1\2022-12-23.txt
> 2. copy below exception message
> 
> Flow Launcher version: 1.10.1
> OS Version: Microsoft Windows NT 10.0.22621.0
> IntPtr Length: 8
> x64: True
> 
> Python Path: 
> Date: 12/23/2022 14:22:23
> Exception:
> Notion Search Exception: 
> Websites: https://github.com/danielduckworth/Flow.Launcher.Plugin.NotionSearch
> Author: Duckworth
> Version: 0.1.5
> Flow.Launcher.Core.ExternalPlugins.FlowPluginException: INFO:root:Integration token found.
> INFO:notional.session:Initialized Notion SDK client
> INFO:notional.session:Retrieving current integration bot
> INFO:root:API token is valid.
> INFO:root:Processing results.
> 
>  ---> System.IO.InvalidDataException: INFO:root:Integration token found.
> INFO:notional.session:Initialized Notion SDK client
> INFO:notional.session:Retrieving current integration bot
> INFO:root:API token is valid.
> INFO:root:Processing results.
> 
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 290
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 295
>    at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 310
>    at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
> --- End of stack trace from previous location ---
>    at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
>    --- End of inner exception stack trace ---
>    at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
>    at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass120_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 730
> --- End of stack trace from previous location ---
>    at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 704
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ```

Thanks @ezxpro, I'll fix this soon. I'm not sure if something with Flow Launcher has changed, the SDK or the official Notion API. It's ganna take a fair bit of digging to figure out.
