### ISSUE TITLE
Notion Search

### ISSUE THREAD

**Issue by modernminimalist** [danielduckworth/Flow.Launcher.Plugin.NotionSearch#5]
I followed the steps to create a notion integration token and added the token to flow launcher notion search plug in.
I then shared one notion page with the integration
But when I search notion from flow launcher it only searches that one page. how do i get it to search everything. thanks

**Comment by dan1mmm** [comment]
You need to share every page you want to able to search!
![image](https://user-images.githubusercontent.com/86565219/177727673-aae679de-19bc-4301-8309-094ac01d0adb.png)
